# replace with python command for python 3
# if python defaults to python 2 on your system.
PY = python
PYTEST = pytest
PYFLAGS =
PYTESTFLAGS = --cov

.PHONY: prog test

prog : 
	$(PY) $(PYFLAGS) main.py

test : 
	$(PYTEST) $(PYTESTFLAGS) SpecGen
